# Generated by Django 5.2.4 on 2025-07-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lot_size', models.IntegerField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('closed', 'Closed')], max_length=50)),
            ],
        ),
    ]
